version: '3.7'

services:
  elogpg:
    image: postgres:13
    restart: on-failure
    container_name: elog_psql
    environment:
      PGTZ: $PGTZ
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
    ports:
      - $POSTGRES_HOST_PORT:5432
    volumes:
      - $PWD/queries:/queries
      - $PWD/queries/init.sql:/docker-entrypoint-initdb.d/init.sql
      - $PWD/data:/var/lib/postgresql/data

  sqlgui:
    image: adminer
    ports:
      - $SQLGUI_HOST_PORT:8080
    environment:
      - ADMINER_DEFAULT_SERVER=$POSTGRES_HOST
      - ADMINER_PLUGINS=tables-filter tinymce
      - ADMINER_DESIGN=pepa-linha
    depends_on:
      - elogpg

  serve:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    command: supervisord
    container_name: elog_flap
    volumes:
      - .:/var/www/
    environment:
      POSTGRES_DB: $POSTGRES_DB
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_HOST: $POSTGRES_HOST

    ports:
      - $SERVER_HOST_PORT:80
      - $DEV_SERVER_HOST_PORT:5000
    depends_on:
      - elogpg
