name: Docker Image CI
on: [push]

jobs:
  code_checks:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [ 3.8, 3.9 ]

    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}
      
      - run: source gitci.sh
      - run: pip install -U pip setuptools wheel -r requirements-dev.txt

      - name: "download essential libraries"
        run: make download

      - name: "build the container"
        run: make build
        
      - name: "Run lint typing test cospell"
        run: make ci
