name: Docker Image CI

#on: [push]

on:
  pull_request:
  push:
    branches: [master]

jobs:

  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Ensure environment variables exist
      run: cp .prime.env .env
    #- name: Build app container
      #run: docker-compose ps
    - name: Ensure code is passing
      run: make ci
