name: Runs 

on:
  pull_request:
  push:
    branches: [master]

jobs:
  lint_python:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.8, 3.9]

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      
      - run: cp .prime.env .env
      - run: pip install -r requirements-dev.txt
      - run: make ci

